image: atlassian/default-image:2
options:
  docker: true
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - chmod +x postscan.sh
          - docker build -f Dockerfile -t dstubked/bitbucket:$BITBUCKET_BUILD_NUMBER --build-arg AQUA_SERVER_URL=$AQUA_SERVER_URL --build-arg AQUA_USERNAME=$AQUA_USERNAME --build-arg AQUA_PASSWORD=$AQUA_PASSWORD --no-cache . > scanout.html.tmp
          - docker images
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker push dstubked/bitbucket:$BITBUCKET_BUILD_NUMBER
        after-script:
          - ./postscan.sh      
        services:
          - docker
    - step:
        script: #Register image in Aqua
          - chmod +x register.sh
          - ./register.sh
